snp_file: "./eigenstrat/v62.0_1240k_public.snp"
ind_file: "./eigenstrat/v62.0_1240k_public.ind"
geno_file: "./eigenstrat/v62.0_1240k_public_eigenstrat.geno"
vcf_file_out: "./vcf/v62.0_1240k_public.vcf"
snp_max:
ind_max: